### ISSUE TITLE
Error loading script: forge_layerdiffusion.py

### ISSUE THREAD

**Issue by saikido** [Zuntan03/EasySdxlWebUi#4]
Pony系のモデルで生成しようとしたところ、下記エラーを得ました。
どのように修復すればよいのでしょうか。

`*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 10, in <module>
        from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
    ModuleNotFoundError: No module named 'diffusers.models.unets'`

また、EasySdxlWebUi全体をアップデートする方法を教えて頂けますと幸いです。

**Comment by Zuntan03** [comment]
https://x.com/Zuntan03/status/1817161707980202078
こちらと同様の症状に見えます。

更新手順は以下のページで案内している
> SdxlWebUi-Update-forge.bat で SdxlWebUi を更新できます。

で更新します。

https://github.com/Zuntan03/EasySdxlWebUi/wiki/EasySdxlWebUi-%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB#%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%89%8B%E9%A0%86

更新の最初に「SdxlWebUi\venv-forge\ を削除しますか？」と問われますが、この件は削除しなくても修正されるはずです。

**Comment by saikido** [comment]
ご対応ありがとうございます。
しかし、どういうわけか肝心のSdxlWebUi-Update-forge.batには何も書かれていない状態でして、実行しても何も起きません。
SdxlWebUi-Update-forge.batの中身をこちらに共有して頂くことは出来ますでしょうか。

よろしくお願い致します。

**Comment by Zuntan03** [comment]
何らかの理由でインストールが失敗しているようですね。

SdxlWebUi-Update-forge.bat の内容はリンク先と同一で、インストール用のbatをリネームしたものになります。
https://github.com/Zuntan03/EasySdxlWebUi/blob/main/SdxlWebUi/setup/Install-EasySdxlWebUi-forge.bat

**Comment by saikido** [comment]
ご回答ありがとうございます。
何とかアップデートはできましたが、今度は画像生成すると下記エラーが出るようになってしまいました。

`Traceback (most recent call last):
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\processing.py", line 922, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\processing.py", line 1275, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 214, in sample
    sigmas = self.get_sigmas(p, steps).to(x.device)
  File "C:\ezSDXL\SdxlWebUi\stable-diffusion-webui-forge\modules\sd_samplers_kdiffusion.py", line 111, in get_sigmas
    sigmas_func = k_diffusion_scheduler[opts.k_sched_type]
KeyError: 'Karras'
'Karras'`

修復方法おわかりでしたらご教示いただけますと幸いです。
それではよろしくお願いいたします。
