### ISSUE TITLE
[解決済] sd-forge-layerdiffuse And LoRA Block Weight Error

### ISSUE THREAD

**Issue by AI-Noel** [Zuntan03/EasySdxlWebUi#5]
いつもお世話になっております。

下記エラーが出ており、どのような対処を行えばよろしいかご教授頂けないでしょうか。
申し訳ございませんが、よろしくお願いいたします。

### ~~LoRA Block Weight 有効時に画像生成~~ ###
```
*** Error running postprocess: F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 843, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 530, in postprocess
        shared.sd_model.forge_objects_after_applying_lora.unet.forge_unpatch_model()
    AttributeError: 'UnetPatcher' object has no attribute 'forge_unpatch_model'
```

### sd-forge-layerdiffuse Forge起動時 ###
#4 にてお答えされているかと思いますが、`SdxlWebUi-Update-forge.bat`で更新を行っても同様のエラーが出ております。
`SdxlWebUi\venv-forge\`を削除してもエラーが出るようで、他何かするべきことがあればご教示頂きたいです。
```
[-] ADetailer initialized. version: 24.3.0, num models: 33
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 10, in <module>
        from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
    ModuleNotFoundError: No module named 'diffusers.models.unets'

```

以上、ご確認の程よろしくお願いいたします。

**Comment by Zuntan03** [comment]
取り急ぎ、すぐに再現できた LoRA Block Weight については、バージョンの巻き戻し対策をいれました。

**Comment by AI-Noel** [comment]
お忙しい中、早々にご対応して頂きましてありがとうございます。

**Comment by Zuntan03** [comment]
手元では確認できていないのですが、ADetailer の件はコマンドプロンプトで
`SdxlWebUi\venv-forge\Scripts\activate`
をした後に
`pip install -U diffusers`
で直るかもしれません。

**Comment by AI-Noel** [comment]
ありがとうございます。
早速試させて頂きましたが、エラーは解消されませんでした。
ただ、`ADetailer`かと思っていたのですが、`sd-forge-layerdiffuse`でエラーが発生しているみたいで
`ADetailer`は関係ございませんでした。お騒がせしてしまい申し訳ございません。
拡張機能で`sd-forge-layerdiffuse`を無効にしたあとForgeを起動するとエラーがなくなりました。

また、`SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse`のフォルダを削除したのち
`SdxlWebUi-Update-forge.bat`を行うとエラーが解消され、問題なく動作するようになりました。

おま環で、お騒がせしてしまい誠に申し訳ございませんでした。
