### ISSUE TITLE
forge更新後に複数の拡張機能エラー

### ISSUE THREAD

**Issue by AI-Noel** [Zuntan03/EasySdxlWebUi#6]
forgeを更新を行ったあと複数の拡張機能でエラーが発生するようになりました。
```
拡張機能の更新時にエラーが発生した場合は、SdxlWebUi/stable-diffusion-webui(-forge)/extensions/ にある拡張機能のフォルダを削除して再更新してください。
```
`extensions`と`extensions-builtin`を削除し更新を行ったのですが、エラーが解消されず困っております。
以下エラー文になります。
```
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\huggingface_hub\__init__.py)

---

*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 8, in <module>
        from diffusers.configuration_utils import ConfigMixin, register_to_config
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\huggingface_hub\__init__.py)

---

*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 5, in <module>
        from scripts.mergers.pluslora import frompromptf
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 21, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 14, in <module>
        import diffusers
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\huggingface_hub\__init__.py)

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\supermerger.py", line 25, in <module>
        import scripts.mergers.pluslora
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 21, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "F:\EasySdxlWebUi\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 14, in <module>
        import diffusers
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (F:\EasySdxlWebUi\SdxlWebUi\venv-forge\lib\site-packages\huggingface_hub\__init__.py)

---
```

エラー文を見る限り下記の拡張機能がエラーとなっているようです。
- /extensions-builtin/forge_preprocessor_marigold
- /extensions/sd-forge-layerdiffuse
- /extensions/sd-webui-supermerger

またコマンドプロンプトにて
```
SdxlWebUi\venv-forge\Scripts\activate
pip install -U diffusers
```
を実行してみましたが、解消されず何か他しないといけないことがございまいしたらご教示頂きたいです
申し訳ございませんが、ご確認の程よろしくお願いいたします。

**Comment by Zuntan03** [comment]
心当たりのある対処を入れました。
問題が解消しているか確認いただけますでしょうか。

huggingface-hub の 0.26 系に問題があるようですので、huggingface-hub==0.25.2 に巻き戻しています。
`pip install huggingface-hub==0.25.2`

**Comment by Zuntan03** [comment]
手元では新規インストールと画像の生成ができました。

**Comment by AI-Noel** [comment]
@Zuntan03 
ありがとうございます！！！
再度、更新を行ったあとすべて解消されました。
迅速なご対応をして頂きまして誠にありがとうございます！！
